### ISSUE TITLE
Output only appears once all tests in a file are finished executing

### ISSUE THREAD

**Issue by zekik64** [mocha-parallel/mocha-parallel-tests#233] opened 2019-04-26 13:52 UTC
When I'm running my suite of tests using mocha-parallel-tests, I only receive any output from my tests AFTER all of the tests in a file have finished executing.

Is there currently a way around this to output as each process is running?

Thanks

**Comment by 1999** [comment] 2019-04-26 22:03
Closing as a duplicate of #226

**Closed by 1999** 2019-04-26 22:03 UTC
